spring:
  application:
    name: chat-server
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: ${PROFILES}
  servlet:
    multipart:
      maxFileSize: 2048MB
      maxRequestSize: 2048MB
  datasource:
    username: root
    password: root
    url: jdbc:mysql://47.93.28.41:3306/easy_chat?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver